/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geometry.gradle;

// import org.junit.Test;
// import static org.junit.Assert.assertEquals;

// public class SphereTest {
//     @Test 
//     public void testSphereVolume() { 
//       Sphere sphere = new Sphere();
//       float result = sphere.volume(2);
//       assertEquals(33.51032, result);
//     }
//   }
